spring:
  profiles:
    include: oauth
  application:
    name: communication_devtools
#  kafka:
#    streams:
#      application-id: test_id
#    bootstrap-servers: localhost:9092
  data:
    redis:
      host: ${REDIS_LOCAL_HOST}
      port: ${REDIS_LOCAL_PORT}
  datasource:
    url: jdbc:mysql://${DB_LOCAL_HOST}/devtools?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
    password: ${DB_LOCAL_PASSWORD}
    username: ${DB_LOCAL_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 30
      idle-timeout: 10
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.hibernate.default_batch_fetch_size: 100
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 9090