spring:
  graphql:
    graphiql:
      enabled: true
    path: /graphql
  kafka:
    consumer:
      bootstrap-servers: http://localhost:9091
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: http://localhost:9091
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: ${REDIS_LOCAL_HOST}
      port: ${REDIS_LOCAL_PORT}
  datasource:
    url: jdbc:mysql://${DB_LOCAL_HOST}/devtools?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
    password: ${DB_LOCAL_PASSWORD}
    username: ${DB_LOCAL_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 30
      idle-timeout: 30000
      max-lifetime: 1800000
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.hibernate.default_batch_fetch_size: 100
    generate-ddl: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  application:
    name: DEVTOOL
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${DEVTOOL_GITHUB_CLIENT_ID}
            client-secret: ${DEVTOOL_GITHUB_CLIENT_SECRET}
            redirect-uri: "http://localhost:9090/login/oauth2/code/github"
            scope:
              - read:user
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

jwt:
  secret: ${DEVTOOL_JWT_SECRET}
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 9090
logging:
  level:
    org.springframework.security: DEBUG
